# Generated by Django 4.0.3 on 2022-07-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0003_accountvo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountvo',
            name='updated',
        ),
        migrations.AlterField(
            model_name='attendee',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
