# Generated by Django 4.0.3 on 2022-07-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0005_alter_attendee_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountvo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
